//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 06:59:05 PM CEST 
//


package com.sos.auth.rest.permission.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sos.auth.rest.permission.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SOSPermissionRole_QNAME = new QName("", "SOSPermissionRole");
    private final static QName _SOSPermission_QNAME = new QName("", "SOSPermission");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sos.auth.rest.permission.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit }
     * 
     */
    public SOSPermissionJocCockpit createSOSPermissionJocCockpit() {
        return new SOSPermissionJocCockpit();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands }
     * 
     */
    public SOSPermissionCommands createSOSPermissionCommands() {
        return new SOSPermissionCommands();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.SubsytemShow }
     * 
     */
    public SOSPermissionCommands.SubsytemShow createSOSPermissionCommandsSubsytemShow() {
        return new SOSPermissionCommands.SubsytemShow();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Lock }
     * 
     */
    public SOSPermissionCommands.Lock createSOSPermissionCommandsLock() {
        return new SOSPermissionCommands.Lock();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.ProcessClass }
     * 
     */
    public SOSPermissionCommands.ProcessClass createSOSPermissionCommandsProcessClass() {
        return new SOSPermissionCommands.ProcessClass();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Job }
     * 
     */
    public SOSPermissionCommands.Job createSOSPermissionCommandsJob() {
        return new SOSPermissionCommands.Job();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Workflow }
     * 
     */
    public SOSPermissionCommands.Workflow createSOSPermissionCommandsWorkflow() {
        return new SOSPermissionCommands.Workflow();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Order }
     * 
     */
    public SOSPermissionCommands.Order createSOSPermissionCommandsOrder() {
        return new SOSPermissionCommands.Order();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.DailyPlan }
     * 
     */
    public SOSPermissionCommands.DailyPlan createSOSPermissionCommandsDailyPlan() {
        return new SOSPermissionCommands.DailyPlan();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7ControllerCluster }
     * 
     */
    public SOSPermissionCommands.JS7ControllerCluster createSOSPermissionCommandsJS7ControllerCluster() {
        return new SOSPermissionCommands.JS7ControllerCluster();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7Controller }
     * 
     */
    public SOSPermissionCommands.JS7Controller createSOSPermissionCommandsJS7Controller() {
        return new SOSPermissionCommands.JS7Controller();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7Controller.Execute }
     * 
     */
    public SOSPermissionCommands.JS7Controller.Execute createSOSPermissionCommandsJS7ControllerExecute() {
        return new SOSPermissionCommands.JS7Controller.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JobStream }
     * 
     */
    public SOSPermissionJocCockpit.JobStream createSOSPermissionJocCockpitJobStream() {
        return new SOSPermissionJocCockpit.JobStream();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JobStream.Change }
     * 
     */
    public SOSPermissionJocCockpit.JobStream.Change createSOSPermissionJocCockpitJobStreamChange() {
        return new SOSPermissionJocCockpit.JobStream.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Joc }
     * 
     */
    public SOSPermissionJocCockpit.Joc createSOSPermissionJocCockpitJoc() {
        return new SOSPermissionJocCockpit.Joc();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Runtime }
     * 
     */
    public SOSPermissionJocCockpit.Runtime createSOSPermissionJocCockpitRuntime() {
        return new SOSPermissionJocCockpit.Runtime();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Calendar }
     * 
     */
    public SOSPermissionJocCockpit.Calendar createSOSPermissionJocCockpitCalendar() {
        return new SOSPermissionJocCockpit.Calendar();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Calendar.Edit }
     * 
     */
    public SOSPermissionJocCockpit.Calendar.Edit createSOSPermissionJocCockpitCalendarEdit() {
        return new SOSPermissionJocCockpit.Calendar.Edit();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Inventory }
     * 
     */
    public SOSPermissionJocCockpit.Inventory createSOSPermissionJocCockpitInventory() {
        return new SOSPermissionJocCockpit.Inventory();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Inventory.Configurations }
     * 
     */
    public SOSPermissionJocCockpit.Inventory.Configurations createSOSPermissionJocCockpitInventoryConfigurations() {
        return new SOSPermissionJocCockpit.Inventory.Configurations();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.YADE }
     * 
     */
    public SOSPermissionJocCockpit.YADE createSOSPermissionJocCockpitYADE() {
        return new SOSPermissionJocCockpit.YADE();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JOCConfigurations }
     * 
     */
    public SOSPermissionJocCockpit.JOCConfigurations createSOSPermissionJocCockpitJOCConfigurations() {
        return new SOSPermissionJocCockpit.JOCConfigurations();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JOCConfigurations.Share }
     * 
     */
    public SOSPermissionJocCockpit.JOCConfigurations.Share createSOSPermissionJocCockpitJOCConfigurationsShare() {
        return new SOSPermissionJocCockpit.JOCConfigurations.Share();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JOCConfigurations.Share.Change }
     * 
     */
    public SOSPermissionJocCockpit.JOCConfigurations.Share.Change createSOSPermissionJocCockpitJOCConfigurationsShareChange() {
        return new SOSPermissionJocCockpit.JOCConfigurations.Share.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.AuditLog }
     * 
     */
    public SOSPermissionJocCockpit.AuditLog createSOSPermissionJocCockpitAuditLog() {
        return new SOSPermissionJocCockpit.AuditLog();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.MaintenanceWindow }
     * 
     */
    public SOSPermissionJocCockpit.MaintenanceWindow createSOSPermissionJocCockpitMaintenanceWindow() {
        return new SOSPermissionJocCockpit.MaintenanceWindow();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.HolidayCalendar }
     * 
     */
    public SOSPermissionJocCockpit.HolidayCalendar createSOSPermissionJocCockpitHolidayCalendar() {
        return new SOSPermissionJocCockpit.HolidayCalendar();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Lock }
     * 
     */
    public SOSPermissionJocCockpit.Lock createSOSPermissionJocCockpitLock() {
        return new SOSPermissionJocCockpit.Lock();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.ProcessClass }
     * 
     */
    public SOSPermissionJocCockpit.ProcessClass createSOSPermissionJocCockpitProcessClass() {
        return new SOSPermissionJocCockpit.ProcessClass();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Job }
     * 
     */
    public SOSPermissionJocCockpit.Job createSOSPermissionJocCockpitJob() {
        return new SOSPermissionJocCockpit.Job();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Workflow }
     * 
     */
    public SOSPermissionJocCockpit.Workflow createSOSPermissionJocCockpitWorkflow() {
        return new SOSPermissionJocCockpit.Workflow();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Order }
     * 
     */
    public SOSPermissionJocCockpit.Order createSOSPermissionJocCockpitOrder() {
        return new SOSPermissionJocCockpit.Order();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.History }
     * 
     */
    public SOSPermissionJocCockpit.History createSOSPermissionJocCockpitHistory() {
        return new SOSPermissionJocCockpit.History();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.DailyPlan }
     * 
     */
    public SOSPermissionJocCockpit.DailyPlan createSOSPermissionJocCockpitDailyPlan() {
        return new SOSPermissionJocCockpit.DailyPlan();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7UniversalAgent }
     * 
     */
    public SOSPermissionJocCockpit.JS7UniversalAgent createSOSPermissionJocCockpitJS7UniversalAgent() {
        return new SOSPermissionJocCockpit.JS7UniversalAgent();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7UniversalAgent.Execute }
     * 
     */
    public SOSPermissionJocCockpit.JS7UniversalAgent.Execute createSOSPermissionJocCockpitJS7UniversalAgentExecute() {
        return new SOSPermissionJocCockpit.JS7UniversalAgent.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7ControllerCluster }
     * 
     */
    public SOSPermissionJocCockpit.JS7ControllerCluster createSOSPermissionJocCockpitJS7ControllerCluster() {
        return new SOSPermissionJocCockpit.JS7ControllerCluster();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7Controller }
     * 
     */
    public SOSPermissionJocCockpit.JS7Controller createSOSPermissionJocCockpitJS7Controller() {
        return new SOSPermissionJocCockpit.JS7Controller();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7Controller.Execute }
     * 
     */
    public SOSPermissionJocCockpit.JS7Controller.Execute createSOSPermissionJocCockpitJS7ControllerExecute() {
        return new SOSPermissionJocCockpit.JS7Controller.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionShiro }
     * 
     */
    public SOSPermissionShiro createSOSPermissionShiro() {
        return new SOSPermissionShiro();
    }

    /**
     * Create an instance of {@link SOSPermissionRoles }
     * 
     */
    public SOSPermissionRoles createSOSPermissionRoles() {
        return new SOSPermissionRoles();
    }

    /**
     * Create an instance of {@link SOSPermissions }
     * 
     */
    public SOSPermissions createSOSPermissions() {
        return new SOSPermissions();
    }

    /**
     * Create an instance of {@link SOSPermissionListCommands }
     * 
     */
    public SOSPermissionListCommands createSOSPermissionListCommands() {
        return new SOSPermissionListCommands();
    }

    /**
     * Create an instance of {@link SOSPermissionListJoc }
     * 
     */
    public SOSPermissionListJoc createSOSPermissionListJoc() {
        return new SOSPermissionListJoc();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Documentation }
     * 
     */
    public SOSPermissionJocCockpit.Documentation createSOSPermissionJocCockpitDocumentation() {
        return new SOSPermissionJocCockpit.Documentation();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.History }
     * 
     */
    public SOSPermissionCommands.History createSOSPermissionCommandsHistory() {
        return new SOSPermissionCommands.History();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpitControllers }
     * 
     */
    public SOSPermissionJocCockpitControllers createSOSPermissionJocCockpitControllers() {
        return new SOSPermissionJocCockpitControllers();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpitController }
     * 
     */
    public SOSPermissionJocCockpitController createSOSPermissionJocCockpitController() {
        return new SOSPermissionJocCockpitController();
    }

    /**
     * Create an instance of {@link SOSPermissionCommandsController }
     * 
     */
    public SOSPermissionCommandsController createSOSPermissionCommandsController() {
        return new SOSPermissionCommandsController();
    }

    /**
     * Create an instance of {@link SOSPermissionCommandsControllers }
     * 
     */
    public SOSPermissionCommandsControllers createSOSPermissionCommandsControllers() {
        return new SOSPermissionCommandsControllers();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.SubsytemShow.View }
     * 
     */
    public SOSPermissionCommands.SubsytemShow.View createSOSPermissionCommandsSubsytemShowView() {
        return new SOSPermissionCommands.SubsytemShow.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Lock.View }
     * 
     */
    public SOSPermissionCommands.Lock.View createSOSPermissionCommandsLockView() {
        return new SOSPermissionCommands.Lock.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Lock.Change }
     * 
     */
    public SOSPermissionCommands.Lock.Change createSOSPermissionCommandsLockChange() {
        return new SOSPermissionCommands.Lock.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.ProcessClass.View }
     * 
     */
    public SOSPermissionCommands.ProcessClass.View createSOSPermissionCommandsProcessClassView() {
        return new SOSPermissionCommands.ProcessClass.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.ProcessClass.Change }
     * 
     */
    public SOSPermissionCommands.ProcessClass.Change createSOSPermissionCommandsProcessClassChange() {
        return new SOSPermissionCommands.ProcessClass.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Job.View }
     * 
     */
    public SOSPermissionCommands.Job.View createSOSPermissionCommandsJobView() {
        return new SOSPermissionCommands.Job.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Job.Execute }
     * 
     */
    public SOSPermissionCommands.Job.Execute createSOSPermissionCommandsJobExecute() {
        return new SOSPermissionCommands.Job.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Job.Change }
     * 
     */
    public SOSPermissionCommands.Job.Change createSOSPermissionCommandsJobChange() {
        return new SOSPermissionCommands.Job.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Workflow.View }
     * 
     */
    public SOSPermissionCommands.Workflow.View createSOSPermissionCommandsWorkflowView() {
        return new SOSPermissionCommands.Workflow.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Workflow.Execute }
     * 
     */
    public SOSPermissionCommands.Workflow.Execute createSOSPermissionCommandsWorkflowExecute() {
        return new SOSPermissionCommands.Workflow.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Workflow.Change }
     * 
     */
    public SOSPermissionCommands.Workflow.Change createSOSPermissionCommandsWorkflowChange() {
        return new SOSPermissionCommands.Workflow.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Order.View }
     * 
     */
    public SOSPermissionCommands.Order.View createSOSPermissionCommandsOrderView() {
        return new SOSPermissionCommands.Order.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Order.Execute }
     * 
     */
    public SOSPermissionCommands.Order.Execute createSOSPermissionCommandsOrderExecute() {
        return new SOSPermissionCommands.Order.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.Order.Change }
     * 
     */
    public SOSPermissionCommands.Order.Change createSOSPermissionCommandsOrderChange() {
        return new SOSPermissionCommands.Order.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.DailyPlan.View }
     * 
     */
    public SOSPermissionCommands.DailyPlan.View createSOSPermissionCommandsDailyPlanView() {
        return new SOSPermissionCommands.DailyPlan.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7ControllerCluster.Execute }
     * 
     */
    public SOSPermissionCommands.JS7ControllerCluster.Execute createSOSPermissionCommandsJS7ControllerClusterExecute() {
        return new SOSPermissionCommands.JS7ControllerCluster.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7Controller.View }
     * 
     */
    public SOSPermissionCommands.JS7Controller.View createSOSPermissionCommandsJS7ControllerView() {
        return new SOSPermissionCommands.JS7Controller.View();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7Controller.Administration }
     * 
     */
    public SOSPermissionCommands.JS7Controller.Administration createSOSPermissionCommandsJS7ControllerAdministration() {
        return new SOSPermissionCommands.JS7Controller.Administration();
    }

    /**
     * Create an instance of {@link SOSPermissionCommands.JS7Controller.Execute.Restart }
     * 
     */
    public SOSPermissionCommands.JS7Controller.Execute.Restart createSOSPermissionCommandsJS7ControllerExecuteRestart() {
        return new SOSPermissionCommands.JS7Controller.Execute.Restart();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JobStream.View }
     * 
     */
    public SOSPermissionJocCockpit.JobStream.View createSOSPermissionJocCockpitJobStreamView() {
        return new SOSPermissionJocCockpit.JobStream.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JobStream.Change.Events }
     * 
     */
    public SOSPermissionJocCockpit.JobStream.Change.Events createSOSPermissionJocCockpitJobStreamChangeEvents() {
        return new SOSPermissionJocCockpit.JobStream.Change.Events();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Joc.View }
     * 
     */
    public SOSPermissionJocCockpit.Joc.View createSOSPermissionJocCockpitJocView() {
        return new SOSPermissionJocCockpit.Joc.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Runtime.Execute }
     * 
     */
    public SOSPermissionJocCockpit.Runtime.Execute createSOSPermissionJocCockpitRuntimeExecute() {
        return new SOSPermissionJocCockpit.Runtime.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Calendar.View }
     * 
     */
    public SOSPermissionJocCockpit.Calendar.View createSOSPermissionJocCockpitCalendarView() {
        return new SOSPermissionJocCockpit.Calendar.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Calendar.Edit.Assign }
     * 
     */
    public SOSPermissionJocCockpit.Calendar.Edit.Assign createSOSPermissionJocCockpitCalendarEditAssign() {
        return new SOSPermissionJocCockpit.Calendar.Edit.Assign();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Inventory.Configurations.Publish }
     * 
     */
    public SOSPermissionJocCockpit.Inventory.Configurations.Publish createSOSPermissionJocCockpitInventoryConfigurationsPublish() {
        return new SOSPermissionJocCockpit.Inventory.Configurations.Publish();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.YADE.View }
     * 
     */
    public SOSPermissionJocCockpit.YADE.View createSOSPermissionJocCockpitYADEView() {
        return new SOSPermissionJocCockpit.YADE.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.YADE.Execute }
     * 
     */
    public SOSPermissionJocCockpit.YADE.Execute createSOSPermissionJocCockpitYADEExecute() {
        return new SOSPermissionJocCockpit.YADE.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.YADE.Configurations }
     * 
     */
    public SOSPermissionJocCockpit.YADE.Configurations createSOSPermissionJocCockpitYADEConfigurations() {
        return new SOSPermissionJocCockpit.YADE.Configurations();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JOCConfigurations.Share.View }
     * 
     */
    public SOSPermissionJocCockpit.JOCConfigurations.Share.View createSOSPermissionJocCockpitJOCConfigurationsShareView() {
        return new SOSPermissionJocCockpit.JOCConfigurations.Share.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JOCConfigurations.Share.Change.SharedStatus }
     * 
     */
    public SOSPermissionJocCockpit.JOCConfigurations.Share.Change.SharedStatus createSOSPermissionJocCockpitJOCConfigurationsShareChangeSharedStatus() {
        return new SOSPermissionJocCockpit.JOCConfigurations.Share.Change.SharedStatus();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.AuditLog.View }
     * 
     */
    public SOSPermissionJocCockpit.AuditLog.View createSOSPermissionJocCockpitAuditLogView() {
        return new SOSPermissionJocCockpit.AuditLog.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.MaintenanceWindow.View }
     * 
     */
    public SOSPermissionJocCockpit.MaintenanceWindow.View createSOSPermissionJocCockpitMaintenanceWindowView() {
        return new SOSPermissionJocCockpit.MaintenanceWindow.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.HolidayCalendar.View }
     * 
     */
    public SOSPermissionJocCockpit.HolidayCalendar.View createSOSPermissionJocCockpitHolidayCalendarView() {
        return new SOSPermissionJocCockpit.HolidayCalendar.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Lock.View }
     * 
     */
    public SOSPermissionJocCockpit.Lock.View createSOSPermissionJocCockpitLockView() {
        return new SOSPermissionJocCockpit.Lock.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.ProcessClass.View }
     * 
     */
    public SOSPermissionJocCockpit.ProcessClass.View createSOSPermissionJocCockpitProcessClassView() {
        return new SOSPermissionJocCockpit.ProcessClass.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Job.View }
     * 
     */
    public SOSPermissionJocCockpit.Job.View createSOSPermissionJocCockpitJobView() {
        return new SOSPermissionJocCockpit.Job.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Job.Change }
     * 
     */
    public SOSPermissionJocCockpit.Job.Change createSOSPermissionJocCockpitJobChange() {
        return new SOSPermissionJocCockpit.Job.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Job.Execute }
     * 
     */
    public SOSPermissionJocCockpit.Job.Execute createSOSPermissionJocCockpitJobExecute() {
        return new SOSPermissionJocCockpit.Job.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Workflow.View }
     * 
     */
    public SOSPermissionJocCockpit.Workflow.View createSOSPermissionJocCockpitWorkflowView() {
        return new SOSPermissionJocCockpit.Workflow.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Workflow.Execute }
     * 
     */
    public SOSPermissionJocCockpit.Workflow.Execute createSOSPermissionJocCockpitWorkflowExecute() {
        return new SOSPermissionJocCockpit.Workflow.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Order.View }
     * 
     */
    public SOSPermissionJocCockpit.Order.View createSOSPermissionJocCockpitOrderView() {
        return new SOSPermissionJocCockpit.Order.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Order.Change }
     * 
     */
    public SOSPermissionJocCockpit.Order.Change createSOSPermissionJocCockpitOrderChange() {
        return new SOSPermissionJocCockpit.Order.Change();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Order.Delete }
     * 
     */
    public SOSPermissionJocCockpit.Order.Delete createSOSPermissionJocCockpitOrderDelete() {
        return new SOSPermissionJocCockpit.Order.Delete();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.Order.Execute }
     * 
     */
    public SOSPermissionJocCockpit.Order.Execute createSOSPermissionJocCockpitOrderExecute() {
        return new SOSPermissionJocCockpit.Order.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.History.View }
     * 
     */
    public SOSPermissionJocCockpit.History.View createSOSPermissionJocCockpitHistoryView() {
        return new SOSPermissionJocCockpit.History.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.DailyPlan.View }
     * 
     */
    public SOSPermissionJocCockpit.DailyPlan.View createSOSPermissionJocCockpitDailyPlanView() {
        return new SOSPermissionJocCockpit.DailyPlan.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7UniversalAgent.View }
     * 
     */
    public SOSPermissionJocCockpit.JS7UniversalAgent.View createSOSPermissionJocCockpitJS7UniversalAgentView() {
        return new SOSPermissionJocCockpit.JS7UniversalAgent.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7UniversalAgent.Execute.Restart }
     * 
     */
    public SOSPermissionJocCockpit.JS7UniversalAgent.Execute.Restart createSOSPermissionJocCockpitJS7UniversalAgentExecuteRestart() {
        return new SOSPermissionJocCockpit.JS7UniversalAgent.Execute.Restart();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7ControllerCluster.View }
     * 
     */
    public SOSPermissionJocCockpit.JS7ControllerCluster.View createSOSPermissionJocCockpitJS7ControllerClusterView() {
        return new SOSPermissionJocCockpit.JS7ControllerCluster.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7ControllerCluster.Execute }
     * 
     */
    public SOSPermissionJocCockpit.JS7ControllerCluster.Execute createSOSPermissionJocCockpitJS7ControllerClusterExecute() {
        return new SOSPermissionJocCockpit.JS7ControllerCluster.Execute();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7Controller.View }
     * 
     */
    public SOSPermissionJocCockpit.JS7Controller.View createSOSPermissionJocCockpitJS7ControllerView() {
        return new SOSPermissionJocCockpit.JS7Controller.View();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7Controller.Administration }
     * 
     */
    public SOSPermissionJocCockpit.JS7Controller.Administration createSOSPermissionJocCockpitJS7ControllerAdministration() {
        return new SOSPermissionJocCockpit.JS7Controller.Administration();
    }

    /**
     * Create an instance of {@link SOSPermissionJocCockpit.JS7Controller.Execute.Restart }
     * 
     */
    public SOSPermissionJocCockpit.JS7Controller.Execute.Restart createSOSPermissionJocCockpitJS7ControllerExecuteRestart() {
        return new SOSPermissionJocCockpit.JS7Controller.Execute.Restart();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SOSPermissionRole")
    public JAXBElement<String> createSOSPermissionRole(String value) {
        return new JAXBElement<String>(_SOSPermissionRole_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "SOSPermission")
    public JAXBElement<String> createSOSPermission(String value) {
        return new JAXBElement<String>(_SOSPermission_QNAME, String.class, null, value);
    }

}
