//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.28 at 11:13:37 PM CEST 
//


package com.sos.auth.rest.permission.model;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}SOSPermissionRoles"/&gt;
 *         &lt;element ref="{}SOSPermissions"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="authenticated" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="access_token" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="security_server_url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sosPermissionRoles",
    "sosPermissions"
})
@XmlRootElement(name = "SOSPermissionShiro")
public class SOSPermissionShiro
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "SOSPermissionRoles", required = true)
    protected SOSPermissionRoles sosPermissionRoles;
    @XmlElement(name = "SOSPermissions", required = true)
    protected SOSPermissions sosPermissions;
    @XmlAttribute(name = "authenticated")
    protected Boolean authenticated;
    @XmlAttribute(name = "user")
    protected String user;
    @XmlAttribute(name = "access_token")
    protected String accessToken;
    @XmlAttribute(name = "security_server_url")
    protected String securityServerUrl;

    /**
     * Gets the value of the sosPermissionRoles property.
     * 
     * @return
     *     possible object is
     *     {@link SOSPermissionRoles }
     *     
     */
    public SOSPermissionRoles getSOSPermissionRoles() {
        return sosPermissionRoles;
    }

    /**
     * Sets the value of the sosPermissionRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOSPermissionRoles }
     *     
     */
    public void setSOSPermissionRoles(SOSPermissionRoles value) {
        this.sosPermissionRoles = value;
    }

    public boolean isSetSOSPermissionRoles() {
        return (this.sosPermissionRoles!= null);
    }

    /**
     * Gets the value of the sosPermissions property.
     * 
     * @return
     *     possible object is
     *     {@link SOSPermissions }
     *     
     */
    public SOSPermissions getSOSPermissions() {
        return sosPermissions;
    }

    /**
     * Sets the value of the sosPermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOSPermissions }
     *     
     */
    public void setSOSPermissions(SOSPermissions value) {
        this.sosPermissions = value;
    }

    public boolean isSetSOSPermissions() {
        return (this.sosPermissions!= null);
    }

    /**
     * Gets the value of the authenticated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAuthenticated() {
        return authenticated;
    }

    /**
     * Sets the value of the authenticated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAuthenticated(boolean value) {
        this.authenticated = value;
    }

    public boolean isSetAuthenticated() {
        return (this.authenticated!= null);
    }

    public void unsetAuthenticated() {
        this.authenticated = null;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    public boolean isSetUser() {
        return (this.user!= null);
    }

    /**
     * Gets the value of the accessToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * Sets the value of the accessToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessToken(String value) {
        this.accessToken = value;
    }

    public boolean isSetAccessToken() {
        return (this.accessToken!= null);
    }

    /**
     * Gets the value of the securityServerUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityServerUrl() {
        return securityServerUrl;
    }

    /**
     * Sets the value of the securityServerUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityServerUrl(String value) {
        this.securityServerUrl = value;
    }

    public boolean isSetSecurityServerUrl() {
        return (this.securityServerUrl!= null);
    }

}
