//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.26 at 02:49:49 PM CEST 
//


package com.sos.auth.rest.permission.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{}SOSPermissionJocCockpitController"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sosPermissionJocCockpitController"
})
@XmlRootElement(name = "SOSPermissionJocCockpitControllers")
public class SOSPermissionJocCockpitControllers
    implements Serializable
{

    private final static long serialVersionUID = 12343L;
    @XmlElement(name = "SOSPermissionJocCockpitController", required = true)
    protected List<SOSPermissionJocCockpitController> sosPermissionJocCockpitController;

    /**
     * Gets the value of the sosPermissionJocCockpitController property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sosPermissionJocCockpitController property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSOSPermissionJocCockpitController().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SOSPermissionJocCockpitController }
     * 
     * 
     */
    public List<SOSPermissionJocCockpitController> getSOSPermissionJocCockpitController() {
        if (sosPermissionJocCockpitController == null) {
            sosPermissionJocCockpitController = new ArrayList<SOSPermissionJocCockpitController>();
        }
        return this.sosPermissionJocCockpitController;
    }

    public boolean isSetSOSPermissionJocCockpitController() {
        return ((this.sosPermissionJocCockpitController!= null)&&(!this.sosPermissionJocCockpitController.isEmpty()));
    }

    public void unsetSOSPermissionJocCockpitController() {
        this.sosPermissionJocCockpitController = null;
    }

}
