type: error
post:
  description: |
    <h2>Starts orders - <b>IN PROGRESS</b></h2>
    <p>this resource can be used in the GUI for three functions</p>
    <ul>
    <li><i>start immediatly</i></li>
    <li><i>start at</i> (with ``scheduledFor``)</li>
    <li><i>start at parametrised</i> (with ``scheduledFor`` and ``arguments``)</li>
    </ul>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="16%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``jobschedulerId``</td><td>required, string</td><td>JobScheduler Controller ID</td><td>jobscheduler</td><td></td></tr>
    <tr><td>``orders``</td><td>required, array</td>
    <td>Specified the orders which should be modified.</td>
    <td> [{
      <div style="padding-left:10px;">"workflow":"/myWorkflow",</div>
      <div style="padding-left:10px;">"orderId":"daily"</div>
      <div style="padding-left:10px;">"scheduledFor":"now+10"</div>
      }]</td>
    <td></td></tr>
    <tr><td>``scheduledFor``</td><td>optional, string<br/>field of each ``orders`` item</td>
    <td>start time in ISO format yyyy-mm-dd HH:MM[:SS] or now or now + HH:MM[:SS] or now + SECONDS</td>
    <td>now+10</td><td>now</td></tr>
    <tr><td>``timeZone``</td><td>optional, string<br/>field of each ``orders`` item</td><td><ul>
       <li>This parameter set the time zone for an absolute time stamp in the ``scheduledFor`` parameter.</li>
       <li>This parameter is ignored for relative times in ``scheduledFor`` such as "now+10"</li>
       <li>See here the list for <a href="https://en.wikipedia.org/wiki/List_of_tz_database_timeZones">available time zones</a>.</li>
    </ul></td><td>Europe/Berlin</td><td>Etc/UTC</td></tr>
    <tr><td>``arguments``</td><td>optional, object<br/>field of each ``orders`` item</td><td>Arguments</td><td>{"key1":"value1","key2":"value2"}</td><td></td></tr>
    <<audit>>
    </tbody></table>

  body:
    application/json:
      schema: startOrders
      example: |
        {
          "jobschedulerId": "jobscheduler",
          "orders": [{
            "orderId": "order1",
            "workflow": "/test/testWorkflow",
            "at": "now"
          }, {
            "orderId": "order2",
            "workflow": "/test/testWorkflow",
            "at": "now"
          }, {
            "orderId": "order3",
            "workflow": "/test/testWorkflow",
            "at": "now"
          }, {
            "orderId": "order4",
            "workflow": "/test/testWorkflow",
            "at": "now"
          }, {
            "orderId": "order5",
            "workflow": "/test/testWorkflow",
            "at": "now"
          }]
        }
  responses:
    200:
      description: It returns an _ok_. This reply code comes only for bulk operations if all commands were successful.
      body:
        application/json:
          schema: ok
          example: |
            {
              "deliveryDate":"2020-08-24T21:13:35Z",
              "surveyDate":"2020-08-24T21:13:34Z",
              "ok":true
            }
    419:
