get?:
  responses:
    400:
      description: |
        **<span style="text-transform: capitalize;"><<resourcePathName>></span> returns error message**
      body:
        text/plain:
post?:
  responses:
    400:
      description: |
        **<span style="text-transform: capitalize;"><<resourcePathName>></span> returns error message**
      body:
        text/plain:
